name: build
on: [push, pull_request]
jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r requirements.txt pyinstaller
      - run: pyinstaller --noconsole --windowed --name "VSCodeWorkspaceLauncher" --icon assets\app.ico --add-data "assets;assets" pyVSCodeLauncher.py
      - uses: actions/upload-artifact@v4
        with: { name: windows-dist, path: dist/VSCodeWorkspaceLauncher/** }

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r requirements.txt pyinstaller
      - run: pyinstaller --noconsole --name "vscode-workspace-launcher" --icon assets/app.png --add-data "assets:assets" pyVSCodeLauncher.py
      - uses: actions/upload-artifact@v4
        with: { name: linux-dist, path: dist/vscode-workspace-launcher/** }